---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: battlemage
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 44 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    install:
      packages:
        - vim
        - nmap
        - zsh
        - pcsc-lite
        - pcsc-lite-ccid
        - opensc
        - pkcs11-provider
        - htop
        - gnome-tweaks
        - gnome-extensions-app
        - fastfetch
        - vlc
        - at-spi2-atk
        - at-spi2-core
        - brltty
        - orca
        - speech-dispatcher
        - gnome-text-editor
        - nautilus
        - yelp
        - adobe-source-code-pro-fonts
        - avahi
        - baobab
        - decibels
        - glycin-thumbnailer
        - gnome-backgrounds
        - gnome-bluetooth
        - gnome-calculator
        - gnome-calendar
        - gnome-characters
        - gnome-clocks
        - gnome-connections
        - gnome-contacts
        - gnome-disk-utility
        - gnome-epub-thumbnailer
        - gnome-font-viewer
        - gnome-logs
        - gnome-maps
        - gnome-remote-desktop
        - gnome-system-monitor
        - gnome-user-docs
        - gnome-user-share
        - gnome-weather
        - localsearch
        - loupe
        - rygel
        - showtime
        - snapshot
        - sushi
        - lollypop
    remove:
      packages:
        # example: removing firefox (in favor of the flatpak)
        # "firefox" is the main package, "firefox-langpacks" is a dependency
        - firefox
        - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)
        - gnome-shell-extension-window-list

  - type: gnome-extensions
    install:
      - 19
      - 1160
      - 517
      - 2087
    uninstall:
      - Apps Menu
      - Background Logo
      - Launch New Instance
      - Places Status Indicator
      #- Window List
      
  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - com.brave.Browser
          - io.frama.editide.editide
          - com.github.tchx84.Flatseal
          - io.github.kolunmi.Bazaar
          - org.libreoffice.LibreOffice
      - scope: user # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
